on:
  workflow_call:
    
jobs:
  validate-tag:
    name: Validate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4   

      - name: Extract and Validate Tag
        run: |
          TAG=${{ github.ref_name }}
          SEMVER_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"
          if [[ $TAG =~ $SEMVER_REGEX ]]; then
            echo "Tag is a valid semantic version: $TAG"
          else
            echo "Invalid semantic version tag: $TAG"
            exit 1
          fi