name: ci for nuget packages

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        default: "9.0.x"
    secrets:
      NUGET_TOKEN:
        required: true

jobs:
  ci: 
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: gainsway
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Configure Nuget sources
        run: dotnet nuget add source --username $GITHUB_OWNER --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$GITHUB_OWNER/index.json"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal