name: publish nuget packages to github packages

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        default: "9.0.x"
    secrets:
      NUGET_TOKEN:
        required: true

jobs:
  validate-tag:
    name: Validate Tag
    if: startsWith(github.ref, 'refs/tags')
    uses: gainsway/github-workflows-public/.github/workflows/job.validate-tag.yml@main
    
  publish:
    runs-on: ubuntu-latest
    needs: validate-tag
    if: needs.validate-tag.result == 'success' || needs.validate-tag.result == 'skipped'
    outputs:
      version: ${{ steps.gitversion.outputs.SemVer }}
      commitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    env:
      GITHUB_OWNER: gainsway
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3
      with:
        versionSpec: "6.0.x"
        includePrerelease: true
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3
      id: gitversion # step id used as reference for output values
      with:
        overrideConfig: |
          tag-prefix: v

    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

    - name: Configure Nuget sources
      run: dotnet nuget add source --username $GITHUB_OWNER --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$GITHUB_OWNER/index.json"

    - name: Package
      run: dotnet pack -p:Version='${{ steps.gitversion.outputs.fullSemVer }}' -c Release --output Publish

    - name: Push package to GitHub packages
      run: dotnet nuget push "Publish/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "github" --skip-duplicate
      